18-auth-and-sessions/cute_rates/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/', to: 'example#testing', as: 'root'
  root to: 'example#testing'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :pets, except: [:destroy]
  resources :people, only: [:show, :index, :new, :create]
end

18-auth-and-sessions/cute_rates/app/models/person.rb
class Person < ApplicationRecord
  has_many :pets
  accepts_nested_attributes_for :pets

  has_secure_password
end

18-auth-and-sessions/cute_rates/app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :person
  validates :name, presence: true
  validates :name, uniqueness: { scope: :person_id,
    message: "can't have two pets with the same name" }
  validates :image, presence: true
end

18-auth-and-sessions/cute_rates/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def authorize!
    unless current_user
      flash[:notice] = "You must be logged in to do that."
      return redirect_to pets_path
    end
  end

  def current_user
    return nil unless session[:person_id]
    @current_user ||= Person.find(session[:person_id])
  end
end

18-auth-and-sessions/cute_rates/app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def testing
    render :testing
  end
end

18-auth-and-sessions/cute_rates/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = Person.find(params[:id])
  end

  def index
    @people = Person.all
  end

  def new
    @person = Person.new
    @person.pets.build
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  private
  def person_params
    params.require(:person).permit(:name, :age, :location,
      pets_attributes: [:name, :image, :likes])
  end
end

18-auth-and-sessions/cute_rates/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authorize!, only: [:new, :create, :edit, :update]

  def index
    @pets = Pet.all
    render :index
  end

  def show
    @pet = Pet.find(params[:id])
    render :show
  end

  def new
    @pet = Pet.new
    @people = Person.all
    render :new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet.id)
    else
      @people = Person.all
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    if @pet.person_id == current_user.id
      @people = Person.all
      render :edit
    else
      flash[:notice] = "You can only edit your own pets."
      redirect_to pets_path
    end
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet.id)
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :image, :likes, :person_id)
  end
end

18-auth-and-sessions/cute_rates/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @person = Person.find_by(username: params[:username])
    if @person && @person.authenticate(params[:password])
      session[:person_id] = @person.id
      redirect_to root_path
    else
      @error = "Login unsuccessful."
      render :new
    end
  end

  def destroy
    session[:person_id] = nil
    redirect_to root_path
  end
end

18-auth-and-sessions/cute_rates/app/helpers/application_helper.rb
module ApplicationHelper
end

18-auth-and-sessions/cute_rates/app/helpers/cute_pets_controller_helper.rb
module CutePetsControllerHelper
end

18-auth-and-sessions/cute_rates/app/views/example/testing.html.erb
<h1>Hello World from Rails</h1>

18-auth-and-sessions/cute_rates/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuteRates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">

    <div id="navbarBasicExample" class="navbar-menu">
      <%= link_to("Home", root_path, class: 'navbar-item') %>
      <%= link_to("Pets", pets_path, class: 'navbar-item') %>
      <%= link_to("People", people_path, class: 'navbar-item') %>
      <% if session[:person_id] %>
        <a href="#">Hi, <%= current_user.name %>!</a>
        <%= link_to("Logout", logout_path, method: :delete, class: 'navbar-item') %>
      <% else %>
        <%= link_to("Login", login_path, class: 'navbar-item') %>
      <% end %>
    </div>
  </nav>

  <% if flash[:notice] %>
    <div class="notification is-warning">
      <p><%= flash[:notice] %></p>
    </div>
  <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

18-auth-and-sessions/cute_rates/app/views/people/index.html.erb
<h1>People with Pets</h1>

<ul>
  <% @people.each do |person| %>
    <li><%= link_to(person.name, person_path(person)) %></li>
  <% end %>
</ul>

<%= link_to("Add a new Person", new_person_path) %>

18-auth-and-sessions/cute_rates/app/views/people/new.html.erb
<h1>Add a new person with pets!</h1>

<%= form_for(@person) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :location %>
  <%= f.text_field :location %>

  <p>Skip the bullshit. Tell me about your dog already.</p>
  <%= f.fields_for(:pets) do |pet_form| %>
    <%= pet_form.label :name %>
    <%= pet_form.text_field :name %>
    <%= pet_form.label :image %>
    <%= pet_form.text_field :image %>
    <%= pet_form.label :likes %>
    <%= pet_form.number_field :likes %>
  <% end %>
  <%= f.submit %>
<% end %>

<%= link_to("List of Humanses", people_path) %>

18-auth-and-sessions/cute_rates/app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<h3><%= @person.age %> in <%= @person.location %></h3>

<h4>With these adorable pets...</h4>

<ul>
  <% @person.pets.each do |pet| %>
    <li><%= link_to(pet.name, pet_path(pet)) %></li>
  <% end %>
</ul>

18-auth-and-sessions/cute_rates/app/views/pets/_form.html.erb
<% if @pet.errors.full_messages.present? %>
  <p>There were some problems saving your data:</p>
  <ul>
    <% @pet.errors.full_messages.each do |msg| %>
      <li style="color: red"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@pet) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Image" %>
  <%= f.text_field :image %>
  <%= f.label "Likes" %>
  <%= f.number_field :likes %>
  <%= f.label "Owner" %>
  <%= f.collection_select(:person_id, @people, :id, :name) %>
  <%= f.submit %>
<% end %>

18-auth-and-sessions/cute_rates/app/views/pets/edit.html.erb
<h1>Editing <%= @pet.name %></h1>

<%= render("form") %>

<br />

<%= link_to("Pets Index", pets_path) %>

18-auth-and-sessions/cute_rates/app/views/pets/index.html.erb
<h1>Look at these cute pets!</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to(pet.name, pet_path(pet)) %></li>
  <% end %>
</ul>

<%= link_to("Add a pet", new_pet_path) %>

18-auth-and-sessions/cute_rates/app/views/pets/new.html.erb
<h1>Add a new pet!</h1>

<%= render("form") %>

<%= link_to("Dogs List", pets_path) %>

18-auth-and-sessions/cute_rates/app/views/pets/show.html.erb
<article class="media">
  <div class="card">
    <div class="card-image">
      <figure class="image is-4by3">
        <img src="<%= @pet.image %>" alt="Placeholder image">
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4"><%= @pet.name %></p>
          <p class="subtitle is-6">Owned by <%= @pet.person.name %></p>
        </div>
      </div>
    </div>
  </div>
</article>

<%= link_to("All Pets", pets_path) %>