15-rails-forms/cute_rates/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'example#testing'

  resources :cute_pets, except: [:destroy]
end

15-rails-forms/cute_rates/app/models/cute_pet.rb
class CutePet < ApplicationRecord
end

15-rails-forms/cute_rates/app/controllers/cute_pets_controller.rb
class CutePetsController < ApplicationController
  def index
    @pets = CutePet.all
    render :index
  end

  def show
    @pet = CutePet.find(params[:id])
    render :show
  end

  def new
    @pet = CutePet.new
    render :new
  end

  def create
    @pet = CutePet.create(pet_params)
    redirect_to cute_pet_path(@pet.id)
    # redirect_to "/cute_pets/#{@pet.id}"
  end

  def edit
    @pet = CutePet.find(params[:id])
    render :edit
  end

  def update
    @pet = CutePet.find(params[:id])
    @pet.update(pet_params)
    redirect_to cute_pet_path(@pet.id)
  end

  private
  def pet_params
    params.permit(:name, :image, :likes)
  end
end

15-rails-forms/cute_rates/app/views/cute_pets/edit.html.erb
<h1>Editing <%= @pet.name %></h1>

<%= render("form") %>

<br />

<%= link_to("Pets Index", cute_pets_path) %>

15-rails-forms/cute_rates/app/views/cute_pets/index.html.erb
<h1>Look at these cute pets!</h1>

<ul>
  <% @pets.each do |pet| %>
  <li><a href="/cute_pets/<%= pet.id %>"><%= pet.name %></a></li>
  <% end %>
</ul>

<a href="/cute_pets/new">Add a new Pet</a>

15-rails-forms/cute_rates/app/views/cute_pets/new.html.erb
<h1>Add a new pet!</h1>

<%= render("form") %>

<%= link_to("Dogs List", cute_pets_path) %>